name: 28584 - Test

on:
  push:
    branches:
      - main

jobs:
  check-tests:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check if test script exists
        id: check_error
        run: |
          if [ ! -f "./test/test.sh" ]; then
            echo "Test script not found!" >&2
            echo "Test script not found!" > napaka.txt
          else
            echo "Test script found." > napaka.txt
          fi

      - name: Upload error file
        uses: actions/upload-artifact@v4
        with:
          name: error-file
          path: napaka.txt

  run-tests:
    needs: check-tests
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download error artifact
        uses: actions/download-artifact@v4
        with:
          name: error-file

      - name: Read error file and check for issues
        run: |
          echo "Error file content:"
          cat napaka.txt
          if grep -q "not found" napaka.txt; then
            echo "Test script is missing. Stopping execution."
            exit 1
          fi

      - name: Prepare test environment
        run: |
          sudo apt update
          sudo apt install -y g++ make

      - name: Compile code
        run: |
          g++ -o radix dn1.cpp

      - name: Run test script
        run: |
          chmod +x ./test/test.sh
          ./test/test.sh
