name: 28584 - Deploy

on:
  workflow_run:
    workflows: ["28584 - Test"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted

    strategy:
      matrix:
        os: [ubuntu-latest]
        version: [v1.0, latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        run: |
          sudo apt update
          sudo apt install -y docker.io
          sudo systemctl start docker
          sudo usermod -aG docker $USER

      - name: Build Docker image
        run: |
          docker build -t arsene5/radix-sort:${{ matrix.version }} .

      - name: Log in to DockerHub
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASS: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin

      - name: Push Docker image
        run: |
          docker push arsene5/radix-sort:${{ matrix.version }}
